# Generated by Django 3.2.10 on 2021-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
