# Generated by Django 3.2.10 on 2021-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20211213_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='PassW0rd', max_length=256),
        ),
    ]
