# Generated by Django 3.2.10 on 2021-12-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Backend.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='related_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
