# Generated by Django 3.2.10 on 2021-12-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20211218_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='from_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Backend.user'),
        ),
    ]
