# Generated by Django 3.2.10 on 2021-12-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_comment_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_name',
        ),
    ]
