# Generated by Django 3.2.10 on 2021-12-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20211219_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
