# Generated by Django 3.2.10 on 2021-12-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
    ]
