# Generated by Django 3.2.10 on 2021-12-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
